# Generated by Django 3.1.5 on 2021-01-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=5)),
                ('last_name', models.CharField(max_length=10)),
                ('gender', models.CharField(default='', max_length=2, null=True)),
                ('age', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
